const staticDevMidiano = "midiano-v1.01"
const expectedCaches = [staticDevMidiano]
const assets = [
    "/",
    "/manifest.json",

    "/index.html",
    "/blackKey.svg",
    "/LandingPageGenerator.js",
    "/serviceWorker.js",

    "/css/bootstrap-theme.min.css",
    "/css/bootstrap.min.css",
    "/css/Inputs.css",
    "/css/Interface.css",
    "/css/landingPage.css",
    "/css/nano.min.css",
    "/css/Settings.css",

    "/favicons/browserconfig.xml",
    "/favicons/favicon-512.png",
    "/favicons/favicon-384.png",
    "/favicons/favicon-128.png",
    "/favicons/favicon-114.png",
    "/favicons/favicon-120.png",
    "/favicons/favicon-144.png",
    "/favicons/favicon-150.png",
    "/favicons/favicon-152.png",
    "/favicons/favicon-16.png",
    "/favicons/favicon-160.png",
    "/favicons/favicon-180.png",
    "/favicons/favicon-192.png",
    "/favicons/favicon-310.png",
    "/favicons/favicon-32.png",
    "/favicons/favicon-57.png",
    "/favicons/favicon-60.png",
    "/favicons/favicon-64.png",
    "/favicons/favicon-70.png",
    "/favicons/favicon-72.png",
    "/favicons/favicon-76.png",
    "/favicons/favicon-96.png",
    "/favicons/favicon.ico",

    "/FluidR3_GM/percussion-mp3.js",
    "/FluidR3_GM/percussion-ogg.js",

    "/fonts/glyphicons-halflings-regular.eot",
    "/fonts/glyphicons-halflings-regular.svg",
    "/fonts/glyphicons-halflings-regular.ttf",
    "/fonts/glyphicons-halflings-regular.woff",
    "/fonts/glyphicons-halflings-regular.woff2",

    "/HQSoundfont/acoustic_grand_piano-mp3.js",
    "/HQSoundfont/acoustic_grand_piano-ogg.js",

    "/images/accidentalFlat.svg",
    "/images/accidentalNatural.svg",
    "/images/accidentalSharp.svg",
    "/images/bgPattern.png",
    "/images/bgScreenshot.png",
    "/images/bgScreenshot2.png",
    "/images/fav.svg",
    "/images/favicon.png",

    "/images/logo3.svg",
    "/images/notehead.svg",
    "/images/openGraphScreen.webp",
    "/images/screenShotNew.webp",
    "/images/subtitle.svg",
    "/images/socials/RedditGrey.svg",
    "/images/socials/TwitterGrey.svg",
    "/images/socials/DiscordGrey.svg",

    "/images/particles/circle_01.png",
    "/images/particles/circle_02.png",
    "/images/particles/circle_03.png",
    "/images/particles/circle_04.png",
    "/images/particles/circle_05.png",
    "/images/particles/dirt_01.png",
    "/images/particles/dirt_02.png",
    "/images/particles/dirt_03.png",
    "/images/particles/fire_01.png",
    "/images/particles/fire_02.png",
    "/images/particles/flame_01.png",
    "/images/particles/flame_02.png",
    "/images/particles/flame_03.png",
    "/images/particles/flame_04.png",
    "/images/particles/flame_05.png",
    "/images/particles/flame_06.png",
    "/images/particles/flare_01.png",
    "/images/particles/light_01.png",
    "/images/particles/light_02.png",
    "/images/particles/light_03.png",
    "/images/particles/magic_01.png",
    "/images/particles/magic_02.png",
    "/images/particles/magic_03.png",
    "/images/particles/magic_04.png",
    "/images/particles/magic_05.png",
    "/images/particles/muzzle_01.png",
    "/images/particles/muzzle_02.png",
    "/images/particles/muzzle_03.png",
    "/images/particles/muzzle_04.png",
    "/images/particles/muzzle_05.png",
    "/images/particles/scorch_01.png",
    "/images/particles/scorch_02.png",
    "/images/particles/scorch_03.png",
    "/images/particles/scratch_01.png",
    "/images/particles/slash_01.png",
    "/images/particles/slash_02.png",
    "/images/particles/slash_03.png",
    "/images/particles/slash_04.png",
    "/images/particles/smoke_01.png",
    "/images/particles/smoke_02.png",
    "/images/particles/smoke_03.png",
    "/images/particles/smoke_04.png",
    "/images/particles/smoke_05.png",
    "/images/particles/smoke_06.png",
    "/images/particles/smoke_07.png",
    "/images/particles/smoke_08.png",
    "/images/particles/smoke_09.png",
    "/images/particles/smoke_10.png",
    "/images/particles/spark_01.png",
    "/images/particles/spark_02.png",
    "/images/particles/spark_03.png",
    "/images/particles/spark_04.png",
    "/images/particles/spark_05.png",
    "/images/particles/spark_06.png",
    "/images/particles/spark_07.png",
    "/images/particles/star_01.png",
    "/images/particles/star_02.png",
    "/images/particles/star_03.png",
    "/images/particles/star_04.png",
    "/images/particles/star_05.png",
    "/images/particles/star_06.png",
    "/images/particles/star_07.png",
    "/images/particles/star_08.png",
    "/images/particles/star_09.png",
    "/images/particles/symbol_01.png",
    "/images/particles/symbol_02.png",
    "/images/particles/trace_01.png",
    "/images/particles/trace_02.png",
    "/images/particles/trace_03.png",
    "/images/particles/trace_04.png",
    "/images/particles/trace_05.png",
    "/images/particles/trace_06.png",
    "/images/particles/trace_07.png",
    "/images/particles/twirl_01.png",
    "/images/particles/twirl_02.png",
    "/images/particles/twirl_03.png",
    "/images/particles/window_01.png",
    "/images/particles/window_02.png",
    "/images/particles/window_03.png",
    "/images/particles/window_04.png",

    "/js/InputListeners.js",
    "/js/jquery-3.3.1.js",
    "/js/main.js",
    "/js/MicInputHandler.js",
    "/js/MidiInputHandler.js",
    "/js/MidiLoader.js",
    "/js/Song.js",
    "/js/SongWorker.js",
    "/js/SoundfontLoader.js",
    "/js/Util.js",

    "/js/audio/AudioNote.js",
    "/js/audio/AudioPlayer.js",
    "/js/audio/Buffers.js",
    "/js/audio/GainNodeController.js",

    "/js/data/CONST.js",
    "/js/data/exampleSongs.json",

    "/js/player/FileLoader.js",
    "/js/player/Player.js",
    "/js/player/Tracks.js",

    "/js/Rendering/BackgroundRender.js",
    "/js/Rendering/DebugRender.js",
    "/js/Rendering/Flowfield.js",
    "/js/Rendering/InSongTextRenderer.js",
    "/js/Rendering/MarkerRenderer.js",
    "/js/Rendering/MeasureLinesRender.js",
    "/js/Rendering/NoteRender.js",
    "/js/Rendering/OverlayRender.js",
    "/js/Rendering/PianoParticleRender.js",
    "/js/Rendering/PianoRender.js",
    "/js/Rendering/ProgressBarRender.js",
    "/js/Rendering/Render.js",
    "/js/Rendering/RenderDimensions.js",
    "/js/Rendering/RenderUtil.js",
    "/js/Rendering/Sequencer.js",
    "/js/Rendering/StreakParticles.js",
    "/js/Rendering/SustainRenderer.js",

    "/js/Rendering/ThreeJs/TheeJsTextureManager.js",
    "/js/Rendering/ThreeJs/ThreeJsBuffer.js",
    "/js/Rendering/ThreeJs/threeJsHandler.js",
    "/js/Rendering/ThreeJs/threeJsParticles.js",
    "/js/Rendering/ThreeJs/threeJsPianoLine.js",
    "/js/Rendering/ThreeJs/ThreeJsSceneManager.js",

    "/js/settings/DefaultParticlePreset.js",
    "/js/settings/DefaultSettings.js",
    "/js/settings/IndexDbHandler.js",
    "/js/settings/LocalStorageHandler.js",
    "/js/settings/ParticlePreset.js",
    "/js/settings/Settings.js",

    "/js/sheet/SheetGenerator.js",
    "/js/sheet/SheetKeyManager.js",
    "/js/sheet/SheetRender.js",

    "/js/ui/ConfirmDialog.js",
    "/js/ui/DomHelper.js",
    "/js/ui/ElementHighlight.js",
    "/js/ui/InputDialogue.js",
    "/js/ui/KeyBinder.js",
    "/js/ui/Loader.js",
    "/js/ui/Notification.js",
    "/js/ui/SettingUI.js",
    "/js/ui/SongUI.js",
    "/js/ui/TrackUI.js",
    "/js/ui/UI.js",
    "/js/ui/ZoomUI.js",

    "/lib/Base64.js",
    "/lib/Base64binary.js",
    "/lib/bootstrap.min.js",
    "/lib/goatCounter.js",
    "/lib/JASMID LICENSE.txt",
    "/lib/jquery-3.3.1.slim.min.js",
    "/lib/perlin.js",
    "/lib/sf2-parser.js",
    "/lib/three.min.js",
    "/lib/three.module1.js",
    "/lib/vexflow-debug.js",
    "/lib/vexflow-debug3.js",
    "/lib/vexflow-min.js",

    "/lib/Pickr/nano.css",
    "/lib/Pickr/pickr.es5.min.js",

    "/metronome/1.wav",
    "/metronome/2.wav",

    "/Reverb/BatteryBenson.wav",
    "/Reverb/BIG HALL E001 M2S.wav",
    "/Reverb/BIG HALL E002 M2S.wav",
    "/Reverb/BIG HALL E003 M2S.wav",
    "/Reverb/Cenzo Celestion V30 Mix 200ms.wav",
    "/Reverb/Cenzo Celestion V30 Mix 500ms.wav",
    "/Reverb/ConradPrebysConcertHallSeatF111.wav",
    "/Reverb/CORRIDOR FLUTTER ECHO E001 M2S.wav",
    "/Reverb/DAMPED CAVE E001 M2S.wav",
    "/Reverb/DAMPED CAVE E002 M2S.wav",
    "/Reverb/DAMPED CAVE E003 M2S.wav",
    "/Reverb/DAMPED CAVE E004 M2S.wav",
    "/Reverb/DAMPED CAVE E005 M2S.wav",
    "/Reverb/DUBWISE E001 M2S.wav",
    "/Reverb/FILTERVERB E001 M2S.wav",
    "/Reverb/FLANGERSPACE E001 M2S.wav",
    "/Reverb/GATED PLACE E001 M2S.wav",
    "/Reverb/HIGH DAMPING CAVE E001 M2S.wav",
    "/Reverb/HOTHALL COMP-1.wav",
    "/Reverb/JFKUnderpass.wav",
    "/Reverb/LARGE DAMPING CAVE E001 M2S.wav",
    "/Reverb/MEDIUM DAMPING CAVE E001 M2S.wav",
    "/Reverb/MEDIUM DAMPING CAVE E002 M2S.wav",
    "/Reverb/MEDIUM DAMPING ROOM E001 M2S.wav",
    "/Reverb/MEDIUM METAL ROOM E001 M2S.wav",
    "/Reverb/MEGA DIFFUSOR E001 M2S.wav",
    "/Reverb/MillsGreekTheater.wav",
    "/Reverb/NaumburgBandshell.wav",
    "/Reverb/PIPE & CARPET E001 M2S.wav",
    "/Reverb/PurgatoryChasm.wav",
    "/Reverb/REVGATEDDL1-1.wav",
    "/Reverb/ROBOTVERB-1.wav",
    "/Reverb/Space4ArtGallery.wav",
    "/Reverb/SteinmanHall.wav",
    "/Reverb/STRANGEBOX-1.wav",
    "/Reverb/TunnelToHeaven.wav",
    "/Reverb/WaterplacePark.wav",
    "/Reverb/WISSTLEPLATE-1.wav",

    "/exampleSongs/piano-midi/alb_esp1.mid",
    "/exampleSongs/piano-midi/alb_esp2.mid",
    "/exampleSongs/piano-midi/alb_esp3.mid",
    "/exampleSongs/piano-midi/alb_esp4.mid",
    "/exampleSongs/piano-midi/alb_esp5.mid",
    "/exampleSongs/piano-midi/alb_esp6.mid",
    "/exampleSongs/piano-midi/alb_se1.mid",
    "/exampleSongs/piano-midi/alb_se2.mid",
    "/exampleSongs/piano-midi/alb_se3.mid",
    "/exampleSongs/piano-midi/alb_se4.mid",
    "/exampleSongs/piano-midi/alb_se5.mid",
    "/exampleSongs/piano-midi/alb_se6.mid",
    "/exampleSongs/piano-midi/alb_se7.mid",
    "/exampleSongs/piano-midi/alb_se8.mid",
    "/exampleSongs/piano-midi/appass_1.mid",
    "/exampleSongs/piano-midi/appass_2.mid",
    "/exampleSongs/piano-midi/appass_3.mid",
    "/exampleSongs/piano-midi/bach_846.mid",
    "/exampleSongs/piano-midi/bach_847.mid",
    "/exampleSongs/piano-midi/bach_850.mid",
    "/exampleSongs/piano-midi/beethoven_hammerklavier_1.mid",
    "/exampleSongs/piano-midi/beethoven_hammerklavier_2.mid",
    "/exampleSongs/piano-midi/beethoven_hammerklavier_3.mid",
    "/exampleSongs/piano-midi/beethoven_hammerklavier_4.mid",
    "/exampleSongs/piano-midi/beethoven_les_adieux_1.mid",
    "/exampleSongs/piano-midi/beethoven_les_adieux_2.mid",
    "/exampleSongs/piano-midi/beethoven_les_adieux_3.mid",
    "/exampleSongs/piano-midi/beethoven_opus10_1.mid",
    "/exampleSongs/piano-midi/beethoven_opus10_2.mid",
    "/exampleSongs/piano-midi/beethoven_opus10_3.mid",
    "/exampleSongs/piano-midi/beethoven_opus22_1.mid",
    "/exampleSongs/piano-midi/beethoven_opus22_2.mid",
    "/exampleSongs/piano-midi/beethoven_opus22_3.mid",
    "/exampleSongs/piano-midi/beethoven_opus22_4.mid",
    "/exampleSongs/piano-midi/beethoven_opus90_1.mid",
    "/exampleSongs/piano-midi/beethoven_opus90_2.mid",
    "/exampleSongs/piano-midi/bor_ps1.mid",
    "/exampleSongs/piano-midi/bor_ps2.mid",
    "/exampleSongs/piano-midi/bor_ps3.mid",
    "/exampleSongs/piano-midi/bor_ps4.mid",
    "/exampleSongs/piano-midi/bor_ps5.mid",
    "/exampleSongs/piano-midi/bor_ps6.mid",
    "/exampleSongs/piano-midi/bor_ps7.mid",
    "/exampleSongs/piano-midi/brahms_opus117_1.mid",
    "/exampleSongs/piano-midi/brahms_opus117_2.mid",
    "/exampleSongs/piano-midi/brahms_opus1_1.mid",
    "/exampleSongs/piano-midi/brahms_opus1_2.mid",
    "/exampleSongs/piano-midi/brahms_opus1_3.mid",
    "/exampleSongs/piano-midi/brahms_opus1_4.mid",
    "/exampleSongs/piano-midi/br_im2.mid",
    "/exampleSongs/piano-midi/br_im5.mid",
    "/exampleSongs/piano-midi/br_im6.mid",
    "/exampleSongs/piano-midi/br_rhap.mid",
    "/exampleSongs/piano-midi/burg_agitato.mid",
    "/exampleSongs/piano-midi/burg_erwachen.mid",
    "/exampleSongs/piano-midi/burg_geschwindigkeit.mid",
    "/exampleSongs/piano-midi/burg_gewitter.mid",
    "/exampleSongs/piano-midi/burg_perlen.mid",
    "/exampleSongs/piano-midi/burg_quelle.mid",
    "/exampleSongs/piano-midi/burg_spinnerlied.mid",
    "/exampleSongs/piano-midi/burg_sylphen.mid",
    "/exampleSongs/piano-midi/burg_trennung.mid",
    "/exampleSongs/piano-midi/chpn-p1.mid",
    "/exampleSongs/piano-midi/chpn-p10.mid",
    "/exampleSongs/piano-midi/chpn-p11.mid",
    "/exampleSongs/piano-midi/chpn-p12.mid",
    "/exampleSongs/piano-midi/chpn-p13.mid",
    "/exampleSongs/piano-midi/chpn-p14.mid",
    "/exampleSongs/piano-midi/chpn-p15.mid",
    "/exampleSongs/piano-midi/chpn-p16.mid",
    "/exampleSongs/piano-midi/chpn-p17.mid",
    "/exampleSongs/piano-midi/chpn-p18.mid",
    "/exampleSongs/piano-midi/chpn-p19.mid",
    "/exampleSongs/piano-midi/chpn-p2.mid",
    "/exampleSongs/piano-midi/chpn-p20.mid",
    "/exampleSongs/piano-midi/chpn-p21.mid",
    "/exampleSongs/piano-midi/chpn-p22.mid",
    "/exampleSongs/piano-midi/chpn-p23.mid",
    "/exampleSongs/piano-midi/chpn-p24.mid",
    "/exampleSongs/piano-midi/chpn-p3.mid",
    "/exampleSongs/piano-midi/chpn-p4.mid",
    "/exampleSongs/piano-midi/chpn-p5.mid",
    "/exampleSongs/piano-midi/chpn-p6.mid",
    "/exampleSongs/piano-midi/chpn-p7.mid",
    "/exampleSongs/piano-midi/chpn-p8.mid",
    "/exampleSongs/piano-midi/chpn-p9.mid",
    "/exampleSongs/piano-midi/chpn_op10_e01.mid",
    "/exampleSongs/piano-midi/chpn_op10_e05.mid",
    "/exampleSongs/piano-midi/chpn_op10_e12.mid",
    "/exampleSongs/piano-midi/chpn_op23.mid",
    "/exampleSongs/piano-midi/chpn_op25_e1.mid",
    "/exampleSongs/piano-midi/chpn_op25_e11.mid",
    "/exampleSongs/piano-midi/chpn_op25_e12.mid",
    "/exampleSongs/piano-midi/chpn_op25_e2.mid",
    "/exampleSongs/piano-midi/chpn_op25_e3.mid",
    "/exampleSongs/piano-midi/chpn_op25_e4.mid",
    "/exampleSongs/piano-midi/chpn_op27_1.mid",
    "/exampleSongs/piano-midi/chpn_op27_2.mid",
    "/exampleSongs/piano-midi/chpn_op33_2.mid",
    "/exampleSongs/piano-midi/chpn_op33_4.mid",
    "/exampleSongs/piano-midi/chpn_op35_1.mid",
    "/exampleSongs/piano-midi/chpn_op35_2.mid",
    "/exampleSongs/piano-midi/chpn_op35_3.mid",
    "/exampleSongs/piano-midi/chpn_op35_4.mid",
    "/exampleSongs/piano-midi/chpn_op53.mid",
    "/exampleSongs/piano-midi/chpn_op66.mid",
    "/exampleSongs/piano-midi/chpn_op7_1.mid",
    "/exampleSongs/piano-midi/chpn_op7_2.mid",
    "/exampleSongs/piano-midi/chp_op18.mid",
    "/exampleSongs/piano-midi/chp_op31.mid",
    "/exampleSongs/piano-midi/debussy_cc_1.mid",
    "/exampleSongs/piano-midi/debussy_cc_2.mid",
    "/exampleSongs/piano-midi/debussy_cc_3.mid",
    "/exampleSongs/piano-midi/debussy_cc_4.mid",
    "/exampleSongs/piano-midi/debussy_cc_5.mid",
    "/exampleSongs/piano-midi/debussy_cc_6.mid",
    "/exampleSongs/piano-midi/deb_clai.mid",
    "/exampleSongs/piano-midi/deb_menu.mid",
    "/exampleSongs/piano-midi/deb_pass.mid",
    "/exampleSongs/piano-midi/deb_prel.mid",
    "/exampleSongs/piano-midi/elise.mid",
    "/exampleSongs/piano-midi/gra_esp_2.mid",
    "/exampleSongs/piano-midi/gra_esp_3.mid",
    "/exampleSongs/piano-midi/gra_esp_4.mid",
    "/exampleSongs/piano-midi/grieg_album.mid",
    "/exampleSongs/piano-midi/grieg_berceuse.mid",
    "/exampleSongs/piano-midi/grieg_brooklet.mid",
    "/exampleSongs/piano-midi/grieg_butterfly.mid",
    "/exampleSongs/piano-midi/grieg_elfentanz.mid",
    "/exampleSongs/piano-midi/grieg_halling.mid",
    "/exampleSongs/piano-midi/grieg_kobold.mid",
    "/exampleSongs/piano-midi/grieg_march.mid",
    "/exampleSongs/piano-midi/grieg_once_upon_a_time.mid",
    "/exampleSongs/piano-midi/grieg_spring.mid",
    "/exampleSongs/piano-midi/grieg_voeglein.mid",
    "/exampleSongs/piano-midi/grieg_waechter.mid",
    "/exampleSongs/piano-midi/grieg_walzer.mid",
    "/exampleSongs/piano-midi/grieg_wanderer.mid",
    "/exampleSongs/piano-midi/grieg_wedding.mid",
    "/exampleSongs/piano-midi/grieg_zwerge.mid",
    "/exampleSongs/piano-midi/haydn_33_1.mid",
    "/exampleSongs/piano-midi/haydn_33_2.mid",
    "/exampleSongs/piano-midi/haydn_33_3.mid",
    "/exampleSongs/piano-midi/haydn_35_1.mid",
    "/exampleSongs/piano-midi/haydn_35_2.mid",
    "/exampleSongs/piano-midi/haydn_35_3.mid",
    "/exampleSongs/piano-midi/haydn_43_1.mid",
    "/exampleSongs/piano-midi/haydn_43_2.mid",
    "/exampleSongs/piano-midi/haydn_43_3.mid",
    "/exampleSongs/piano-midi/haydn_7_1.mid",
    "/exampleSongs/piano-midi/haydn_7_2.mid",
    "/exampleSongs/piano-midi/haydn_7_3.mid",
    "/exampleSongs/piano-midi/haydn_8_1.mid",
    "/exampleSongs/piano-midi/haydn_8_2.mid",
    "/exampleSongs/piano-midi/haydn_8_3.mid",
    "/exampleSongs/piano-midi/haydn_8_4.mid",
    "/exampleSongs/piano-midi/haydn_9_1.mid",
    "/exampleSongs/piano-midi/haydn_9_2.mid",
    "/exampleSongs/piano-midi/haydn_9_3.mid",
    "/exampleSongs/piano-midi/hay_40_1.mid",
    "/exampleSongs/piano-midi/hay_40_2.mid",
    "/exampleSongs/piano-midi/islamei.mid",
    "/exampleSongs/piano-midi/liz_donjuan.mid",
    "/exampleSongs/piano-midi/liz_et1.mid",
    "/exampleSongs/piano-midi/liz_et2.mid",
    "/exampleSongs/piano-midi/liz_et3.mid",
    "/exampleSongs/piano-midi/liz_et4.mid",
    "/exampleSongs/piano-midi/liz_et5.mid",
    "/exampleSongs/piano-midi/liz_et6.mid",
    "/exampleSongs/piano-midi/liz_et_trans4.mid",
    "/exampleSongs/piano-midi/liz_et_trans5.mid",
    "/exampleSongs/piano-midi/liz_et_trans8.mid",
    "/exampleSongs/piano-midi/liz_liebestraum.mid",
    "/exampleSongs/piano-midi/liz_rhap02.mid",
    "/exampleSongs/piano-midi/liz_rhap09.mid",
    "/exampleSongs/piano-midi/liz_rhap10.mid",
    "/exampleSongs/piano-midi/liz_rhap12.mid",
    "/exampleSongs/piano-midi/liz_rhap15.mid",
    "/exampleSongs/piano-midi/mendel_op19_1.mid",
    "/exampleSongs/piano-midi/mendel_op19_2.mid",
    "/exampleSongs/piano-midi/mendel_op19_3.mid",
    "/exampleSongs/piano-midi/mendel_op19_4.mid",
    "/exampleSongs/piano-midi/mendel_op19_5.mid",
    "/exampleSongs/piano-midi/mendel_op19_6.mid",
    "/exampleSongs/piano-midi/mendel_op30_1.mid",
    "/exampleSongs/piano-midi/mendel_op30_2.mid",
    "/exampleSongs/piano-midi/mendel_op30_3.mid",
    "/exampleSongs/piano-midi/mendel_op30_4.mid",
    "/exampleSongs/piano-midi/mendel_op30_5.mid",
    "/exampleSongs/piano-midi/mendel_op53_5.mid",
    "/exampleSongs/piano-midi/mendel_op62_3.mid",
    "/exampleSongs/piano-midi/mendel_op62_4.mid",
    "/exampleSongs/piano-midi/mendel_op62_5.mid",
    "/exampleSongs/piano-midi/mond_1.mid",
    "/exampleSongs/piano-midi/mond_2.mid",
    "/exampleSongs/piano-midi/mond_3.mid",
    "/exampleSongs/piano-midi/muss_1.mid",
    "/exampleSongs/piano-midi/muss_2.mid",
    "/exampleSongs/piano-midi/muss_3.mid",
    "/exampleSongs/piano-midi/muss_4.mid",
    "/exampleSongs/piano-midi/muss_5.mid",
    "/exampleSongs/piano-midi/muss_6.mid",
    "/exampleSongs/piano-midi/muss_7.mid",
    "/exampleSongs/piano-midi/muss_8.mid",
    "/exampleSongs/piano-midi/mz_311_1.mid",
    "/exampleSongs/piano-midi/mz_311_2.mid",
    "/exampleSongs/piano-midi/mz_311_3.mid",
    "/exampleSongs/piano-midi/mz_330_1.mid",
    "/exampleSongs/piano-midi/mz_330_2.mid",
    "/exampleSongs/piano-midi/mz_330_3.mid",
    "/exampleSongs/piano-midi/mz_331_1.mid",
    "/exampleSongs/piano-midi/mz_331_2.mid",
    "/exampleSongs/piano-midi/mz_331_3.mid",
    "/exampleSongs/piano-midi/mz_332_1.mid",
    "/exampleSongs/piano-midi/mz_332_2.mid",
    "/exampleSongs/piano-midi/mz_332_3.mid",
    "/exampleSongs/piano-midi/mz_333_1.mid",
    "/exampleSongs/piano-midi/mz_333_2.mid",
    "/exampleSongs/piano-midi/mz_333_3.mid",
    "/exampleSongs/piano-midi/mz_545_1.mid",
    "/exampleSongs/piano-midi/mz_545_2.mid",
    "/exampleSongs/piano-midi/mz_545_3.mid",
    "/exampleSongs/piano-midi/mz_570_1.mid",
    "/exampleSongs/piano-midi/mz_570_2.mid",
    "/exampleSongs/piano-midi/mz_570_3.mid",
    "/exampleSongs/piano-midi/pathetique_1.mid",
    "/exampleSongs/piano-midi/pathetique_2.mid",
    "/exampleSongs/piano-midi/pathetique_3.mid",
    "/exampleSongs/piano-midi/schubert_D850_1.mid",
    "/exampleSongs/piano-midi/schubert_D850_2.mid",
    "/exampleSongs/piano-midi/schubert_D850_3.mid",
    "/exampleSongs/piano-midi/schubert_D850_4.mid",
    "/exampleSongs/piano-midi/schubert_D935_1.mid",
    "/exampleSongs/piano-midi/schubert_D935_2.mid",
    "/exampleSongs/piano-midi/schubert_D935_3.mid",
    "/exampleSongs/piano-midi/schubert_D935_4.mid",
    "/exampleSongs/piano-midi/schub_d760_1.mid",
    "/exampleSongs/piano-midi/schub_d760_2.mid",
    "/exampleSongs/piano-midi/schub_d760_3.mid",
    "/exampleSongs/piano-midi/schub_d760_4.mid",
    "/exampleSongs/piano-midi/schub_d960_1.mid",
    "/exampleSongs/piano-midi/schub_d960_2.mid",
    "/exampleSongs/piano-midi/schub_d960_3.mid",
    "/exampleSongs/piano-midi/schub_d960_4.mid",
    "/exampleSongs/piano-midi/schuim-1.mid",
    "/exampleSongs/piano-midi/schuim-2.mid",
    "/exampleSongs/piano-midi/schuim-3.mid",
    "/exampleSongs/piano-midi/schuim-4.mid",
    "/exampleSongs/piano-midi/schumm-1.mid",
    "/exampleSongs/piano-midi/schumm-2.mid",
    "/exampleSongs/piano-midi/schumm-3.mid",
    "/exampleSongs/piano-midi/schumm-4.mid",
    "/exampleSongs/piano-midi/schumm-5.mid",
    "/exampleSongs/piano-midi/schumm-6.mid",
    "/exampleSongs/piano-midi/schum_abegg.mid",
    "/exampleSongs/piano-midi/schu_143_1.mid",
    "/exampleSongs/piano-midi/schu_143_2.mid",
    "/exampleSongs/piano-midi/schu_143_3.mid",
    "/exampleSongs/piano-midi/scn15_1.mid",
    "/exampleSongs/piano-midi/scn15_10.mid",
    "/exampleSongs/piano-midi/scn15_11.mid",
    "/exampleSongs/piano-midi/scn15_12.mid",
    "/exampleSongs/piano-midi/scn15_13.mid",
    "/exampleSongs/piano-midi/scn15_2.mid",
    "/exampleSongs/piano-midi/scn15_3.mid",
    "/exampleSongs/piano-midi/scn15_4.mid",
    "/exampleSongs/piano-midi/scn15_5.mid",
    "/exampleSongs/piano-midi/scn15_6.mid",
    "/exampleSongs/piano-midi/scn15_7.mid",
    "/exampleSongs/piano-midi/scn15_8.mid",
    "/exampleSongs/piano-midi/scn15_9.mid",
    "/exampleSongs/piano-midi/scn16_1.mid",
    "/exampleSongs/piano-midi/scn16_2.mid",
    "/exampleSongs/piano-midi/scn16_3.mid",
    "/exampleSongs/piano-midi/scn16_4.mid",
    "/exampleSongs/piano-midi/scn16_5.mid",
    "/exampleSongs/piano-midi/scn16_6.mid",
    "/exampleSongs/piano-midi/scn16_7.mid",
    "/exampleSongs/piano-midi/scn16_8.mid",
    "/exampleSongs/piano-midi/scn68_10.mid",
    "/exampleSongs/piano-midi/scn68_12.mid",
    "/exampleSongs/piano-midi/ty_april.mid",
    "/exampleSongs/piano-midi/ty_august.mid",
    "/exampleSongs/piano-midi/ty_dezember.mid",
    "/exampleSongs/piano-midi/ty_februar.mid",
    "/exampleSongs/piano-midi/ty_januar.mid",
    "/exampleSongs/piano-midi/ty_juli.mid",
    "/exampleSongs/piano-midi/ty_juni.mid",
    "/exampleSongs/piano-midi/ty_maerz.mid",
    "/exampleSongs/piano-midi/ty_mai.mid",
    "/exampleSongs/piano-midi/ty_november.mid",
    "/exampleSongs/piano-midi/ty_oktober.mid",
    "/exampleSongs/piano-midi/ty_september.mid",
    "/exampleSongs/piano-midi/waldstein_1.mid",
    "/exampleSongs/piano-midi/waldstein_2.mid",
    "/exampleSongs/piano-midi/waldstein_3.mid"
]

self.addEventListener("install", installEvent => {
    installEvent.waitUntil(
        caches.open(staticDevMidiano).then(cache => {
            assets.forEach(asset => {
                // console.log("Installing" + asset)
                try {
                    cache
                        .add(asset)
                        .catch(e => console.log("Error adding to cache" + asset))
                } catch (e) {
                    console.log(e)
                }
            })
            // cache.addAll(assets)
        })
    )
})
self.addEventListener("activate", event => {
    // delete any caches that aren't in expectedCaches
    // which will get rid of static-v1

    event.waitUntil(
        caches
        .keys()
        .then(keys =>
            Promise.all(
                keys.map(key => {
                    if (!expectedCaches.includes(key)) {
                        console.log("Deleting old cache " + key)
                        return caches.delete(key)
                    }
                })
            )
        )
        .then(() => {
            console.log(staticDevMidiano + " now ready.")
        })
    )
})
self.addEventListener("fetch", fetchEvent => {
    fetchEvent.respondWith(
        caches
        .match(fetchEvent.request)
        .then(res => {
            if (res) {
                // console.log("Found " + fetchEvent.request.url + " in cache")
                return res
            }
            // console.log("fetching " + fetchEvent.request.url)
            return fetch(fetchEvent.request)
        })
        .catch(function(error) {
            return caches.match("index.html")
        })
    )
})