import {
    CONST
} from "../data/CONST.js"

export const getDefaultPresets = () => defaultPresets
const defaultPresets = [{
        particlePresetName: "Sparks & Bubbles",
        types: [{
                particleTypeName: "Particles_Swirl_Right",
                particlesTexture: "star_06",
                particleAmount: "25",
                particleOverrideColor: false,
                particleColor: "rgba(255,0,0,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: "1",
                particleSize: "14",
                particleSpeedX: "3.7",
                particleSpeedY: "7.1",
                particleLife: "94",
                particleRising: "1.5",
                particlesShrink: "1",
                particlesRotation: "0",
                particlesRotationRandom: 180,
                particlesRotationSpeed: "0.465",
                particlesFriction: "0.418",
                turbulenceXFrequency: "0.7",
                turbulenceYFrequency: "0.4",
                turbulenceXAmplitude: "40",
                turbulenceYAmplitude: "100",
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across note",
                particleDistributionZ: "Behind notes"
            },
            {
                particleTypeName: "Flare_On_Keys",
                particlesTexture: "magic_03",
                particleAmount: "20",
                particleOverrideColor: false,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "0.35",
                particleSpeed: "2",
                particleSize: "30",
                particleSpeedX: "0",
                particleSpeedY: "0.4",
                particleLife: "46",
                particleRising: "0",
                particlesShrink: "1",
                particlesRotation: 0.25,
                particlesRotationRandom: 180,
                particlesRotationSpeed: "0.2",
                particlesFriction: "0",
                turbulenceXFrequency: "0",
                turbulenceYFrequency: "0",
                turbulenceXAmplitude: "59",
                turbulenceYAmplitude: "0",
                particleFadeOut: "0",
                particleYOffset: "2",
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano"
            },
            {
                particleTypeName: "Particles_Background",
                particlesTexture: "circle_05",
                particleAmount: "1.45",
                particleOverrideColor: false,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: "1",
                particleSize: "37",
                particleSpeedX: "1.1",
                particleSpeedY: "11.3",
                particleLife: "63",
                particleRising: "0",
                particlesShrink: "1",
                particlesRotation: 0.25,
                particlesRotationRandom: 180,
                particlesRotationSpeed: "0.2",
                particlesFriction: "0.02",
                turbulenceXFrequency: "0",
                turbulenceYFrequency: "0",
                turbulenceXAmplitude: "0",
                turbulenceYAmplitude: "0",
                particleFadeOut: "0",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across note",
                particleDistributionZ: "Behind notes"
            },
            {
                particleTypeName: "Particles_Bottom",
                particlesTexture: "spark_02",
                particleAmount: "8.49",
                particleOverrideColor: false,
                particleColor: "rgba(255,0,0,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: "1",
                particleSize: "22",
                particleSpeedX: "8.1",
                particleSpeedY: "-7.4",
                particleLife: "94",
                particleRising: "-1.5",
                particlesShrink: "1",
                particlesRotation: "0",
                particlesRotationRandom: 180,
                particlesRotationSpeed: "0.465",
                particlesFriction: "0.418",
                turbulenceXFrequency: "0.09",
                turbulenceYFrequency: "0.4",
                turbulenceXAmplitude: "40",
                turbulenceYAmplitude: "0",
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Bottom of keys",
                particleDistributionZ: "Behind Piano / front of notes"
            }
        ]
    },
    {
        particlePresetName: "Sparks",
        types: [{
                particleTypeName: "Particles_Swirl_Right",
                particlesTexture: "trace_07",
                particleAmount: "2.75",
                particleOverrideColor: false,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: "1",
                particleSize: "28",
                particleSpeedX: "3.7",
                particleSpeedY: "7.1",
                particleLife: "94",
                particleRising: "1.5",
                particlesShrink: "0",
                particlesRotation: "0",
                particlesRotationSpeed: "0.465",
                particlesFriction: "0.418",
                turbulenceXFrequency: "0.7",
                turbulenceYFrequency: "0.4",
                turbulenceXAmplitude: "40",
                turbulenceYAmplitude: "100",
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across note",
                particleDistributionZ: "Behind Piano / front of notes",
                ticker: 0.88
            },
            {
                particleTypeName: "Flare_On_Keys",
                particlesTexture: "light_03",
                particleAmount: "20",
                particleOverrideColor: false,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "0.19",
                particleSpeed: "2",
                particleSize: "28",
                particleSpeedX: "0",
                particleSpeedY: "0.1",
                particleLife: "46",
                particleRising: "0.7",
                particlesShrink: "1",
                particlesRotation: 0.25,
                particlesRotationSpeed: "0.2",
                particlesFriction: "0",
                turbulenceXFrequency: "0",
                turbulenceYFrequency: "0",
                turbulenceXAmplitude: "59",
                turbulenceYAmplitude: "0",
                particleFadeOut: "0",
                particleYOffset: "-4",
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano",
                ticker: 0
            }
        ]
    },

    {
        particlePresetName: "Bubbles",
        types: [{
                particleTypeName: "Bubbles",
                particlesTexture: "circle_05",
                particleAmount: "2.28",
                particleOverrideColor: false,
                particleColor: "rgba(0,150,0,1)",
                particlesBlending: "Additive",
                particlesOpacity: 1,
                particleSpeed: 1,
                particleSize: "22",
                particleSpeedX: "2.9",
                particleSpeedY: 2,
                particleLife: "217",
                particleRising: "1.9",
                particlesShrink: "0",
                particlesRotation: 0.5,
                particlesRotationSpeed: 0.02,
                particlesFriction: "0.037",
                turbulenceXFrequency: "0.35",
                turbulenceYFrequency: "0.29",
                turbulenceXAmplitude: "27",
                turbulenceYAmplitude: "72",
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "Behind notes",
                ticker: 0
            },
            {
                particleTypeName: "Bubbles_on_top",
                particlesTexture: "circle_05",
                particleAmount: "25",
                particleOverrideColor: false,
                particleColor: "rgba(0,150,0,1)",
                particlesBlending: "Additive",
                particlesOpacity: 1,
                particleSpeed: 1,
                particleSize: "22",
                particleSpeedX: "4",
                particleSpeedY: "6.9",
                particleLife: "30",
                particleRising: "1.9",
                particlesShrink: "1",
                particlesRotation: "0",
                particlesRotationSpeed: "0",
                particlesFriction: "0.037",
                turbulenceXFrequency: "0",
                turbulenceYFrequency: "0",
                turbulenceXAmplitude: "0",
                turbulenceYAmplitude: "0",
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano",
                ticker: 0
            }
        ]
    },
    {
        particlePresetName: "Fountain",
        types: [{
                particleTypeName: "RisingVertically",
                particlesTexture: "circle_05",
                particleAmount: "12",
                particleOverrideColor: false,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: 1,
                particleSpeed: 1,
                particleSize: "60",
                particleSpeedX: 0,
                particleSpeedY: "2.8",
                particleLife: "134",
                particleRising: 0.1,
                particlesShrink: 1,
                particlesRotation: 0.5,
                particlesRotationSpeed: 0.02,
                particlesFriction: 0,
                turbulenceXFrequency: 0,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 0,
                turbulenceYAmplitude: 0,
                particleFadeOut: 0,
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "Behind Piano / front of notes",
                ticker: 0
            },
            {
                particleTypeName: "SpreadOut",
                particlesTexture: "circle_05",
                particleAmount: 10,
                particleOverrideColor: false,
                particleColor: "rgba(161,132,132,1)",
                particlesBlending: "Additive",
                particlesOpacity: 1,
                particleSpeed: 2,
                particleSize: 10,
                particleSpeedX: 2,
                particleSpeedY: 5,
                particleLife: 500,
                particleRising: -0.5,
                particlesShrink: 0.5,
                particlesRotation: 0.25,
                particlesRotationSpeed: 0.01,
                particlesFriction: 0.01,
                turbulenceXFrequency: 1,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 0,
                turbulenceYAmplitude: 1,
                particleFadeOut: 1,
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "Behind Piano / front of notes",
                ticker: 0
            }
        ]
    },
    {
        particlePresetName: "Stars",
        types: [{
                particleTypeName: "Stars",
                particlesTexture: "star_09",
                particleAmount: "0.33",
                particleOverrideColor: true,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: 2,
                particleSize: "40",
                particleSpeedX: 2,
                particleSpeedY: "33.2",
                particleLife: "147",
                particleRising: "0",
                particlesShrink: "0",
                particlesRotation: "63",
                particlesRotationSpeed: 0.01,
                particlesFriction: "0.062",
                turbulenceXFrequency: 1,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 0,
                turbulenceYAmplitude: 1,
                particleFadeOut: 1,
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano",
                ticker: 0
            },
            {
                particleTypeName: "Smoke",
                particlesTexture: "smoke_05",
                particleAmount: "25",
                particleOverrideColor: false,
                particleColor: "rgba(0,150,0,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: "1",
                particleSize: "38",
                particleSpeedX: "4.3",
                particleSpeedY: "0",
                particleLife: "13",
                particleRising: "0",
                particlesShrink: "0",
                particlesRotation: "360",
                particlesRotationSpeed: "0.053",
                particlesFriction: "0",
                turbulenceXFrequency: "0.18",
                turbulenceYFrequency: "0.23",
                turbulenceXAmplitude: "1",
                turbulenceYAmplitude: "0",
                particleFadeOut: 0,
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across note",
                particleDistributionZ: "Behind Piano / front of notes",
                ticker: 0
            },
            {
                particleTypeName: "Circles",
                particlesTexture: "circle_04",
                particleAmount: "25",
                particleOverrideColor: true,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "1",
                particleSpeed: 2,
                particleSize: "40",
                particleSpeedX: "1.4",
                particleSpeedY: "2.9",
                particleLife: "64",
                particleRising: "0",
                particlesShrink: "1",
                particlesRotation: "63",
                particlesRotationSpeed: 0.01,
                particlesFriction: "0.033",
                turbulenceXFrequency: 1,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 0,
                turbulenceYAmplitude: 1,
                particleFadeOut: 1,
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano",
                ticker: 0
            }
        ]
    },

    {
        particlePresetName: "Burning",
        types: [{
                particleTypeName: "Smoke",
                particlesTexture: "smoke_07",
                particleAmount: "5",
                particleOverrideColor: true,
                particleColor: "rgba(255,255,255,1)",
                particlesBlending: "Additive",
                particlesOpacity: "0.05",
                particleSpeed: 1,
                particleSize: "100",
                particleSpeedX: "0.5",
                particleSpeedY: "0.5",
                particleLife: "150",
                particleRising: "0.8",
                particlesShrink: "1",
                particlesRotation: 360,
                particlesRotationSpeed: 0.02,
                particlesFriction: "0.02",
                turbulenceXFrequency: 0.25,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 10,
                turbulenceYAmplitude: 0,
                particleFadeOut: "1",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Top of keys",
                particleDistributionZ: "In front of piano"
            },
            {
                particleTypeName: "OnNotes",
                particlesTexture: "scorch_03",
                particleAmount: "20",
                particleOverrideColor: false,
                particleColor: "rgba(255,234,59,1)",
                particlesBlending: "Additive",
                particlesOpacity: "0.6",
                particleSpeed: "1",
                particleSize: "50",
                particleSpeedX: 0,
                particleSpeedY: "2",
                particleLife: "15",
                particleRising: "0",
                particlesShrink: "0",
                particlesRotation: "360",
                particlesRotationSpeed: 0.01,
                particlesFriction: "0",
                turbulenceXFrequency: 0.15,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 50,
                turbulenceYAmplitude: 0,
                particleFadeOut: "0",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across note",
                particleDistributionZ: "Behind Piano / front of notes"
            },
            {
                particleTypeName: "OnKeys",
                particlesTexture: "scorch_03",
                particleAmount: "15",
                particleOverrideColor: false,
                particleColor: "rgba(156,38,176,1)",
                particlesBlending: "Additive",
                particlesOpacity: "0.6",
                particleSpeed: "1",
                particleSize: "80",
                particleSpeedX: "0",
                particleSpeedY: "1.9",
                particleLife: "15",
                particleRising: "0",
                particlesShrink: "0",
                particlesRotation: "360",
                particlesRotationSpeed: 0.01,
                particlesFriction: "0",
                turbulenceXFrequency: 1,
                turbulenceYFrequency: 0,
                turbulenceXAmplitude: 0,
                turbulenceYAmplitude: 1,
                particleFadeOut: "0",
                particleYOffset: 0,
                particleDistributionX: "Across note",
                particleDistributionY: "Across keys",
                particleDistributionZ: "In front of piano"
            }
        ]
    },
    {
        particlePresetName: "Disintegrate",
        types: [{
            particleTypeName: "Rising",
            particlesTexture: "window_03",
            particleAmount: "25",
            particleOverrideColor: false,
            particleColor: "rgba(255,255,255,1)",
            particlesBlending: "Additive",
            particlesOpacity: "0.25",
            particleSpeed: 2,
            particleSize: "50",
            particleSpeedX: "0",
            particleSpeedY: "2.5",
            particleLife: 200,
            particleRising: "0",
            particlesShrink: "1",
            particlesRotation: 0.25,
            particlesRotationSpeed: "0.2",
            particlesFriction: 0.01,
            turbulenceXFrequency: 1,
            turbulenceYFrequency: 0,
            turbulenceXAmplitude: 0,
            turbulenceYAmplitude: 1,
            particleFadeOut: 1,
            particleYOffset: 0,
            particleDistributionX: "Across note",
            particleDistributionY: "Across note",
            particleDistributionZ: "Behind Piano / front of notes"
        }]
    }
]